
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
- script: npm install
- script: npm test
- task: PowerShell@2
  inputs:
    filePath: 'scripts/ProcessTemplates.ps1'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: processedTemplates